### ISSUE TITLE
Decouple vendor package

### ISSUE THREAD

**Issue by chrisvogt** [paulredmond/chosen-cakephp#16]
Should the Chosen assets be installed through another source? (E.g. Bower, Composer). Would be nice to see the vendor package decoupled from this plug-in. At the very least, if someone didn't want to use a package manager, they could always [download the archive](https://github.com/harvesthq/chosen/releases/tag/1.0.0) of the release and follow instructions to drop the contents in the /webroot directory, or wherever would be best.

Thoughts?

**Comment by paulredmond** [comment]
I wrestled with this and decided it was way easier to just package the Chosen assets alongside the plugin, and made the plugin more portable without having to do much extra work. It just works out of the box.

As it stands right now, this plugin adds the scripts/css no matter what. Perhaps a good compromise would be to enable/disable loading the Chosen assets in the helper (enabled by default). That way the user can use their own Bower setup and scripts or whatever they want.

How does that sound?

**Comment by chrisvogt** [comment]
It is nice that it works out of the box, especially after spending time trying to prod Travis into placing the packages in the right location with Bower. :8ball: I'm going to test two methods - bower and as a git submodule - and will link them to this thread when they are passing tests if they seem useful.

**Comment by chrisvogt** [comment]
Closing this for now.
